services:
  # Blockchain Infrastructure Services Only
  proof-server:
    container_name: 'midnight-forge-proof-server'
    image: "midnightnetwork/proof-server:4.0.0"
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
    networks:
      - midnight-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB

  indexer:
    container_name: 'midnight-forge-indexer'
    image: 'midnightntwrk/indexer-standalone:2.1.1'
    ports:
      - '8088:8088'
    environment:
      RUST_LOG: "indexer=info,chain_indexer=info,indexer_api=info,wallet_indexer=info,indexer_common=info,fastrace_opentelemetry=off,info"
      # Random 32-byte hex-encoded secret used to make the standalone indexer run.
      # Only needed to satisfy the config schema – not meant for secure use.
      APP__INFRA__SECRET: "303132333435363738393031323334353637383930313233343536373839303132"
      APP__INFRA__NODE__URL: "ws://node:9944"
    depends_on:
      node:
        condition: service_started
    networks:
      - midnight-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768MB
        reservations:
          memory: 384MB

  node:
    image: 'midnightnetwork/midnight-node:0.12.0'
    platform: linux/amd64
    ports:
      - "9944:9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 120s
    environment:
      CFG_PRESET: "dev"
    networks:
      - midnight-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1.5GB
        reservations:
          memory: 768MB

networks:
  midnight-network:
    driver: bridge 