services:
  # Blockchain Infrastructure Services
  proof-server:
    container_name: 'midnight-forge-proof-server'
    image: "midnightnetwork/proof-server:4.0.0"
    ports:
      - "6300:6300"
    environment:
      RUST_BACKTRACE: "full"
    networks:
      - midnight-network
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB

  indexer:
    container_name: 'midnight-forge-indexer'
    image: 'midnightntwrk/indexer-standalone:2.1.1'
    ports:
      - '8088:8088'
    environment:
      RUST_LOG: "indexer=info,chain_indexer=info,indexer_api=info,wallet_indexer=info,indexer_common=info,fastrace_opentelemetry=off,info"
      # Random 32-byte hex-encoded secret used to make the standalone indexer run.
      # Only needed to satisfy the config schema – not meant for secure use.
      APP__INFRA__SECRET: "303132333435363738393031323334353637383930313233343536373839303132"
      APP__INFRA__NODE__URL: "ws://node:9944"
    depends_on:
      node:
        condition: service_started
    networks:
      - midnight-network
    deploy:
      resources:
        limits:
          memory: 768MB
        reservations:
          memory: 384MB

  node:
    image: 'midnightnetwork/midnight-node:0.12.0'
    container_name: 'midnight-forge-node'
    ports:
      - "9944:9944"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9944/health" ]
      interval: 2s
      timeout: 5s
      retries: 5
      start_period: 40s
    environment:
      CFG_PRESET: "dev"
    networks:
      - midnight-network
    deploy:
      resources:
        limits:
          memory: 1.5GB
        reservations:
          memory: 768MB

  # Application Services
  midnight-forge-server:
    container_name: 'midnight-forge-server'
    build:
      context: .
      dockerfile: midnight-forge-server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: "development"
      PORT: "3001"
      INDEXER_URL: "http://indexer:8088"
      PROOF_SERVER_URL: "http://proof-server:6300"
      NODE_URL: "ws://node:9944"
    depends_on:
      - indexer
      - proof-server
      - node
    networks:
      - midnight-network
    volumes:
      - ./midnight-forge-server:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 256MB

  midnight-forge-webapp:
    container_name: 'midnight-forge-webapp'
    build:
      context: ./midnight-forge-webapp-vite
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_SERVER_URL: "http://localhost:3001"
      VITE_INDEXER_URL: "http://localhost:8088"
    depends_on:
      - midnight-forge-server
    networks:
      - midnight-network
    volumes:
      - ./midnight-forge-webapp-vite:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512MB
        reservations:
          memory: 256MB

networks:
  midnight-network:
    driver: bridge 